// <auto-generated />
using System;
using CosmeticsEvaluator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmeticsEvaluator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407174750_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.EvaluationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalVerdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MlProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReviewScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("EvaluationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
