// <auto-generated />
using System;
using CosmeticsEvaluator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CosmeticsEvaluator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.EvaluationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalVerdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MlProbability")
                        .HasColumnType("REAL");

                    b.Property<int>("NOfLoves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NOfReviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("PricePerOunce")
                        .HasColumnType("REAL");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ReviewScore")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EvaluationHistory");
                });

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.ProductCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryAcneTreatments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryAntiAging")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryBlottingPapers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryExfoliators")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryEyeTreatments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFaceMasks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFaceOils")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFaceSerums")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFaceSunscreen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFaceWash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryFacialPeels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryMistsEssences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryMoisturizerTreatments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryMoisturizers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryNightCreams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryToners")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NOfLoves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NOfReviews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double?>("PricePerOunce")
                        .HasColumnType("REAL");

                    b.Property<double>("ReviewScore")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ProductCatalog");
                });

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainConcern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.EvaluationEntry", b =>
                {
                    b.HasOne("CosmeticsEvaluator.Api.Models.User", "User")
                        .WithMany("Evaluations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CosmeticsEvaluator.Api.Models.User", b =>
                {
                    b.Navigation("Evaluations");
                });
#pragma warning restore 612, 618
        }
    }
}
